# not yet finished
---
- block:
    - name: install apt debs
      apt: name={{ item }} state=latest
      with_items:
        - apt-transport-https 
        - ca-certificates
    - name: setup apt key for docker 
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
    - name: delete docker apt source list file
      file: path=/etc/apt/sources.list.d/docker.list state=absent
    - name: recreate docker apt source list file
      lineinfile: dest=/etc/apt/sources.list.d/docker.list create=yes line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
      #deb https://apt.dockerproject.org/repo ubuntu-trusty main
    - name: update apt
      apt: update_cache=yes
    - name: purge lxc-docker
      apt: name=lxc-docker purge=yes
      ignore_errors: true

  become: true
  when: ansible_distribution == "Ubuntu"
  tags: [docker]

- name: ensure jenkins container
  become: true
  docker:
    name: localjenkins
    image: jenkins
    state: started
    memory_limit: "512MB"
    ports:
      - "8080:8080"
    volumes:
      - "{{ ws.user.name }}/var/jenkins:/var/jenkins_home"
  tags:
    - jenkins
